### ISSUE TITLE
Attestation Agent no longer accessible to workload container

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/guest-components#171]
It seems that the switch to ttRPC has broken our ability to make a request to the AA from the workload. This is a significant regression. @mkulke and @jepio may have more details. 

We might need to switch back to the gRPC feature or think about implementing a separate API for the workload to contact the AA.

**Comment by surajssd** [comment]
I think the appropriate title is `AA no longer accessible to workload container over network` which definitely is a regression.

**Comment by mkulke** [comment]
related: https://github.com/confidential-containers/documentation/issues/131

**Comment by Xynnn007** [comment]
close this issue as https://github.com/confidential-containers/guest-components/pull/325 opens a RESTful for app containers to get evidence and attestation token.
