### ISSUE TITLE
[RFC] ocicrypt rustify plan

### ISSUE THREAD

**Issue by arronwy** [confidential-containers/guest-components#182]
As we synced in last ocicrypt rustify architecture review meeting, @lumjjb also shared the following suggested implementation plan:

![image](https://user-images.githubusercontent.com/13145624/122319158-d1428e80-cf52-11eb-9d54-3d04615f56d3.png)

In order to accelerate the process and different teams can cooperation in parallel. I seperate the work with different module in seperate steps:
# Step1: Implement base struct and create config API
* [x]  spec
* [x]  config
* [x]  helpers
# Step2: Implement keywrapper for asymmetric key and utils for key parse and verify
* [x]  JWE
* [ ]  PGP
* [ ]  PKCS7
* [ ]  PKCS11
* [ ] utils
# Step3: Implement blockcipher and keyprovider for symmetric key encryption/decryption and retriverment
* [x]  blockcipher
* [x] keyprovider
# Step4: Implement EncryptLayer/DecryptLayer API and integration tests 
* [x] EncryptLayer/DecryptLayer API
* [x] integration tests 
* [x] CI/CD
![image](https://user-images.githubusercontent.com/13145624/122321347-4cf20a80-cf56-11eb-9b33-014e97848957.png)

# Step5: Integration with Kata Agent
 According to Confidential Containers V0 Plan: https://docs.google.com/spreadsheets/d/1M_MijAutym4hMg8KtIye1jIDAUMUWsFCri9nq4dqGvA/edit#gid=0 , we will support image offload in guest. The initial implementation will be skopeo + ocicrypt + umoci to download/decrypt/upack. The next step can be rustify the process, using rust oci crate to download container image, ocicrypt-rs to decrypt and umoci to unpack. Finally we may implement our own oci registry client and image service in kata agent:
![cc](https://user-images.githubusercontent.com/13145624/133576729-4283e0a2-e82c-4fd3-9cc8-4c385b03e203.PNG)

**Comment by fitzthum** [comment]
I think we can close this. Please reopen if we still need it for something.
