### ISSUE TITLE
Publish vendor and source code tarballs together when doing releases.

### ISSUE THREAD

**Issue by etrunko** [confidential-containers/guest-components#189]
When building for distros such as Fedora and RHEL, there is usually no access to the internet, causing errors when cargo vendor is run. In order to fix this, people maintaining such packages have to run the command themselves and then patch the original source code, adding the vendored code.

Other projects such as [kata-containers](https://github.com/kata-containers/kata-containers/issues/1203),  and mdevctl already publish both source and vendor codes in separate tarballs, ensuring that code is buildable even though some other project used gets deprecated and/or deleted.

**Comment by fidencio** [comment]
Closing this as a dup of https://github.com/confidential-containers/guest-components/issues/554
