### ISSUE TITLE
Missing Cargo.lock file

### ISSUE THREAD

**Issue by katexochen** [confidential-containers/guest-components#268]
There is no Cargo.lock file commited in this repo, as it is listed in the .gitignore file. We should commit the lock file to prevent supply chain security issues.

**Comment by katexochen** [comment]
Thinking about it, this repo now contains library code as well as binary code within the same workspace. I'm not sure what that means for the lock file. The docs state you should [commit Cargo.lock for binaries, but ignore it for libraries](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

**Comment by Xynnn007** [comment]
Oh, thanks for bringing this. There is a commit https://github.com/confidential-containers/guest-components/pull/272/commits/125c7abe23ca7b07d2fa3935a94a5d91b174a839 not sure if it is suitable?

**Comment by katexochen** [comment]
@Xynnn007 I think we should discuss this first. I'm quite new to Rust, so I'm not sure this is the right thing to to. As said, image-rs and ocicrypt-rs are libraries, and I'm not sure what committing Cargo.lock would mean for consumers outside this repo.
