### ISSUE TITLE
[Security Risk] Enable of security validation mechanism.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/guest-components#30]
At present, the security validation function is enabled through the Config of image-rs, but we must consider the risk in actual use: there may be malicious boot image providers, which disable the security validation function by providing wrong image-rs configuration.

Therefore, do we need to consider forcibly enabling security validation in the code of image-rs?

**Comment by ariel-adam** [comment]
@jialez0 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
