### ISSUE TITLE
`cargo test` cannot pass due to csv-rs doesn't support openssl version:806354976

### ISSUE THREAD

**Issue by chendave** [confidential-containers/guest-components#346]
the issue can be found from here:
https://github.com/confidential-containers/guest-components/actions/runs/6105168876/job/16568311628?pr=321

```
Error: failed to run custom build command for `csv-rs v0.1.0 (https://gitee.com/anolis/csv-rs?rev=bcf3bcc#bcf3bcc0)`
Caused by:
  process didn't exit successfully: `/home/runner/work/guest-components/guest-components/target/debug/build/csv-rs-c4227a814abf3087/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unsupported openssl version:806354976', /home/runner/.cargo/git/checkouts/csv-rs-6ce26198efa2f606/bcf3bcc/build.rs:19:18
```

and can be verified locally, 
```
cargo test --features openssl,rust-crypto,offline_fs_kbc -p attestation-agent -p attester -p coco_keyprovider -p kbc -p kbs_protocol -p attestation_agent -p crypto -p resource_uri -p sev@0.1.0
```

Tried to revert the change here: https://github.com/confidential-containers/guest-components/pull/342, but still doesn't work.

```
  = note: /usr/bin/ld: /go/src/github.com/confidential-containers/guest-components/target/debug/deps/libcsv_rs-cf8059eec6404d4e.rlib(csv_rs-cf8059eec6404d4e.csv_rs.fbdd6b72ef39f42a-cgu.11.rcgu.o): undefined reference to symbol 'EVP_PKEY_set_alias_type@@OPENSSL_1_1_1'
          /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

**Comment by chendave** [comment]
cc @Xynnn007 @BaoshunFang

**Comment by chendave** [comment]
cc @jialez0

**Comment by BaoshunFang** [comment]
@chendave csv-rs only support openssl 3.0.x, which is also the version of rust:latest. But the current revision of [azure-cvm-tooling](https://github.com/kinvolk/azure-cvm-tooling) set vendored feature to openssl, which will build openssl from source, and the version is 3.1.2. So I think the way to fix the issue is update azure-cvm-tooling to 09a8a0d or newer, this version disabled vendored feature.
CC @jialez0 . same issue as attestation-service.

**Comment by chendave** [comment]
> which will build openssl from source, and the version is 3.1.2. 

I think the source is here:
https://github.com/sfackler/rust-openssl

the latest version is 0.10.57

the change from `azure-cvm-tooling` upstream, 
 memoffset = "0.8.0"
```patch
-openssl = { version = "0.10.45", features = ["vendored"], optional = true }
+openssl = { version = "0.10", optional = true }
```

so, the bump to 09a8a0d should not work, I have verified, it doesn't work as well.
