### ISSUE TITLE
github workflow improvements

### ISSUE THREAD

**Issue by mythi** [confidential-containers/guest-components#352]
- [ ] from #350, I can see lots of duplicates. Move to something like `uses: "./.github/workflows/lib-common.yaml"` and `needs: xyz` 
- [ ] from #380, [pin DCAP versions](https://download.01.org/intel-sgx/sgx_repo/ubuntu/apt_preference_files/) to match packages with crate versions

**Comment by Xynnn007** [comment]
cc @jialez0
