### ISSUE TITLE
Cannot build attestation agent with rust 1.69.0

### ISSUE THREAD

**Issue by surajssd** [confidential-containers/guest-components#354]
The build fails as follows:

```bash
$ cargo build --release --no-default-features --features " online_sev_kbc ttrpc,rust-crypto" --target x86_64-unknown-linux-musl
    Updating git repository `https://github.com/krustlet/oci-distribution.git`
    Updating crates.io index
    Updating git repository `https://github.com/kinvolk/azure-cvm-tooling`
    Updating git repository `https://gitee.com/anolis/csv-rs`
...
  Downloaded ring v0.16.20
  Downloaded 249 crates (30.9 MB) in 1.58s (largest was `prost-build` at 8.4 MB)
error: package `anstyle v1.0.3` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p anstyle@1.0.3 --precise ver
where `ver` is the latest version of `anstyle` supporting rustc 1.69.0
```

Steps to recreate this failed state (I did this in a rust 1.69 docker container: `docker run -it rust:1.69.0-buster bash`):

```bash
rustc --version
rustup target add x86_64-unknown-linux-musl

git clone https://github.com/confidential-containers/guest-components
cd guest-components/attestation-agent/app
git checkout 12018c4f0137d1cb6317a00126850f892c70993a
cargo build --release --no-default-features --features " online_sev_kbc ttrpc,rust-crypto" --target x86_64-unknown-linux-musl
```

To fix this run the following command and build again:

```bash
cargo update -p anstyle@1.0.3 --precise 1.0.2
```

What's confusing is that when I run the aforementioned command nothing changes in the `Cargo.toml` or anywhere else, so not sure how to fix this in code/config.

**Comment by surajssd** [comment]
Interestingly, a `Cargo.lock` file is created and that has anstyle mentioned in there. Hmm, I wonder if we should fix this #268

**Comment by stevenhorsman** [comment]
Maybe I've misunderstood, but I think Beraldo's lock file has anstyle 1.0.2, which doesn't have the rust 1.70 dependency, so we should be ok with that? I'm also updating kata-containers to use 1.72, but I agree that the lockfile is the right approach

**Comment by stevenhorsman** [comment]
Yep - just merged it now as we need to unblock, whilst the Cargo.lock conversations continue. I have follow up PRs for peer pods and guest-components in the works

**Comment by stevenhorsman** [comment]
FYI https://github.com/confidential-containers/guest-components/pull/356 is the 1.72 bump in testing here

**Comment by surajssd** [comment]
Thanks @stevenhorsman

**Comment by stevenhorsman** [comment]
Hey Suraj, are you happy to close this, now we've got the Cargo.lock merged and bumped the default rust version - which doesn't technically solve your issue, but should stop it happening again?

**Comment by surajssd** [comment]
SGTM Steve!
