### ISSUE TITLE
AA: Now AA does not support providing KBS TLS cert.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/guest-components#367]
Now, in the `kbs_protocol` library, the `KbsClient` support providing KBS TLS cert through `set_kbs_cert()`, but in the `attestation-agent` library and binary, there is no way to set KBS TLS cert. We need add this function.

**Comment by Xynnn007** [comment]
Refer to example  configuration file https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/attestation-agent/config.example.toml
