### ISSUE TITLE
Invalid encryption keys: Provided protocol not recognized

### ISSUE THREAD

**Issue by pegahnikbakht** [confidential-containers/guest-components#400]
Hi, 

We are trying to encrypt a docker image with a key from coco_keyprovider for example I used the following command to encrypt the docker image 
`OCICRYPT_KEYPROVIDER_CONFIG=newocicrypt.conf skopeo copy --encryption-key provider:attestation-agent:sample=true  oci:alpine oci:encrypted`

But I get the following error: 
`FATA[0000] Invalid encryption keys: Provided protocol not recognized `

Any idea why it might happens?

**Comment by Xynnn007** [comment]
Hi @pegahnikbakht could you share more context to reproduce the error?

btw, the error seems from `skopeo`

**Comment by fitzthum** [comment]
You might double check that skopeo can find the ocicrypt config you specific and that the file is formatted correctly.

**Comment by pegahnikbakht** [comment]
Hi, yeah the problem was skopeo version, I updated and it works fine now.
