### ISSUE TITLE
image-rs re-introduce ring version that is incompatible with s390x?

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/guest-components#422]
I'm not completely sure what the situation is, so apologies if this isn't clear.

During testing of https://github.com/kata-containers/kata-containers/pull/8670, we ran the kata-agent build with a new commit from image-rs and they failed with:
```
13:13:34 error: failed to run custom build command for `ring v0.16.20`
13:13:34 
13:13:34 Caused by:
13:13:34   process didn't exit successfully: `/kata-containers/src/agent/target/release/build/ring-884cb6961366a545/build-script-build` (exit status: 101)
13:13:34   --- stderr
13:13:34   thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/index.crates.io-d11c229612889eed/ring-0.16.20/build.rs:358:10
```
I know ring didn't use to support s390x. That got added in October in https://github.com/briansmith/ring/pull/1297, but 0.16.20 is ~3 years old, so it won't be in there. I know that Ding did some work to ensure that ring wasn't needed to unblock s390x builds of image-rs, has that been undone recently?

It seems to be commit https://github.com/confidential-containers/guest-components/commit/4ddac3882c1aed1ab562a4fa10d587ff464fcc1e that introduced this issue as a151bca worked, so we just used that one in the end, but once we re-integrate image-rs with kata-containers we'll hit this issue.

For some of the other guest-components projects we have [Makefiles](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/Makefile) to make it easier to build for multiple architectures and added workflows: https://github.com/confidential-containers/guest-components/blob/5d4bb95578b611d15d6907b3419f5cb129572e51/.github/workflows/cdh_basic.yml#L59-L61 that test them, so maybe we need to consider this for image-rs so we can find out about issues before them get integrated with kata-containers?

**Comment by mythi** [comment]
> Ding did some work to ensure that ring wasn't needed to unblock s390x builds of image-rs, has that been undone recently?

Looks like the latest sigstore pulls "tough" which depends on this old ring... :/

**Comment by mythi** [comment]
sigstore-rs has a dependabot PR open that brings in updated ring. We should just get them to upgrade and cut a new release?

**Comment by Xynnn007** [comment]
Let me fix the dep in upstream sigstore-rs.

**Comment by Xynnn007** [comment]
pending pr https://github.com/sigstore/sigstore-rs/pull/320

**Comment by Xynnn007** [comment]
Before we get the upstream fixed, do you think it is urgent that we need to fix by changing the current sigstore-rs rev to my personal repo? @stevenhorsman

**Comment by stevenhorsman** [comment]
> Before we get the upstream fixed, do you think it is urgent that we need to fix by changing the current sigstore-rs rev to my personal repo? @stevenhorsman

Hey Ding, I'm not completely caught up yet, but I don't think it's super urgent right now. I mostly raised it to try and get a fix once we are ready to merge the image-rs working into kata-agent in `main`, which I hope is very soon, but at this point probably not worth switching to a fork. Thanks!

**Comment by ChengyuZhu6** [comment]
@stevenhorsman @Xynnn007 I have encountered this problem in guest-pull PR in s390x and ppc64le:
https://github.com/kata-containers/kata-containers/actions/runs/8047127851/job/21975784913?pr=8484
https://github.com/kata-containers/kata-containers/actions/runs/8047127851/job/21975803238?pr=8484
https://github.com/kata-containers/kata-containers/actions/runs/8047127851/job/21975808824?pr=8484
https://github.com/kata-containers/kata-containers/actions/runs/8047127851/job/21975789375?pr=8484

**Comment by Xynnn007** [comment]
> How far have we come in addressing this issue?

Oh. This is a long stack.

1. `image-rs` depends on `sigstore-rs`.
2. `sigstore-rs` depends on `tough 0.14`.
3. `tough 0.14.0` depends on `ring 0.16`. But `tough 0.16` depends on `ring 0.17`.
4. `ring 0.16` does not support s390x and ppc64le but `ring 0.17` supports.

I made [a PR](https://github.com/sigstore/sigstore-rs/pull/320) in sigstore-rs to update `tough` to `0.16` but CI fails, which I also made a PR to fix in `tough` https://github.com/awslabs/tough/pull/737.

What we should do now is
1. wait for tough community to publish a new release including the fix. (I have pinged them in the slack channel half a week ago)
2. Update the https://github.com/sigstore/sigstore-rs/pull/320 and get it merge
3. Update the sigstore version in `guest-components/image-rs`

**Comment by mythi** [comment]
> Oh. This is a long stack.
> 
>     1. `image-rs` depends on `sigstore-rs`.
> 
>     2. `sigstore-rs` depends on `tough 0.14`.

@Xynnn007 Correct me if I'm wrong but I believe 2. got added because cosign client could not be built without `tuf` feature anymore. I submitted an issue about it separately: https://github.com/sigstore/sigstore-rs/issues/318 So perhaps we don't need all of those dependencies but try to make `tuf` optional? It seems there's some work ongoing for that already

**Comment by Xynnn007** [comment]
> @Xynnn007 Correct me if I'm wrong but I believe 2. got added because cosign client could not be built without `tuf` feature anymore. I submitted an issue about it separately: [sigstore/sigstore-rs#318](https://github.com/sigstore/sigstore-rs/issues/318) So perhaps we don't need all of those dependencies but try to make `tuf` optional? It seems there's some work ongoing for that already

Right. Both will resolve this but the thread you mentioned seems faster as we do not require one more community. I have reviewed the code of that. Either of them is merged could handle the problem of this issue.

**Comment by stevenhorsman** [comment]
FYI I've created draft PR https://github.com/confidential-containers/guest-components/pull/491 to add testing of s390x and powerpc64le so when this is fixed we can try and stop any regressions quicker

**Comment by mkulke** [comment]
https://www.memorysafety.org/blog/rustls-with-aws-crypto-back-end-and-fips/

we might want to use AWS' backend via feature flag if that compiles on S360

**Comment by Xynnn007** [comment]
> we might want to use AWS' backend via feature flag if that compiles on S390x

It's a good idea, but the fully replacement of `ring` by [aws-lc-rs](https://github.com/aws/aws-lc-rs) requires indirect dependency packages that depend on ring need to be corrected as well. : |

**Comment by mkulke** [comment]
> It's a good idea, but the fully replacement of `ring` by [aws-lc-rs](https://github.com/aws/aws-lc-rs) requires indirect dependency packages that depend on ring need to be corrected as well. : |

ahh, it's a transitive dep. yes, this won't help.

**Comment by mythi** [comment]
> > we might want to use AWS' backend via feature flag if that compiles on S390x
> 
> It's a good idea, but the fully replacement of `ring` by [aws-lc-rs](https://github.com/aws/aws-lc-rs) requires indirect dependency packages that depend on ring need to be corrected as well. : |

I believe the topic worth discussing is can we default to one stack on all platforms/architectures going forward to reduce dependencies and simplify the code base/features.
