### ISSUE TITLE
How to build CDH with only RESOURCE_PROVIDER and no KMS

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/guest-components#435]
Currently CDH will build all KMSes if PROVIDER is empty - https://github.com/confidential-containers/guest-components/tree/main/confidential-data-hub#supported-features

Is there a way to build CDH without any KMSes and use only KBS. 
For example something like `make RESOURCE_PROVIDER=kbs PROVIDER=none`

cc @Xynnn007 @fitzthum @arronwy

**Comment by fitzthum** [comment]
This seems like a good idea. 

I also think we might want to rename the `PROVIDER` config to make things a bit more clear.

**Comment by bpradipt** [comment]
> This seems like a good idea.
> 
> I also think we might want to rename the `PROVIDER` config to make things a bit more clear.

Probably rename PROVIDER to KMS to align with the purpose
