### ISSUE TITLE
ci: connectivity problems to csv-rs repo

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#443]
Unfortunately there seem to be persistent connectivity issues to gitee.com from github runners. I noticed similar problems in my local and corporate (western european) networks. builds would regularly just fail because it couldn't successfully retrieve the csv-rs dep from gitee.com.

Can we use a github/gitlab/... mirror or reference the dep through other means?

<img width="482" alt="image" src="https://github.com/confidential-containers/guest-components/assets/273280/00df7815-2c2a-406e-9d76-748124d1ff6b">

[example gh action run](https://github.com/confidential-containers/guest-components/actions/runs/7580803267/job/20647230532)

**Comment by Xynnn007** [comment]
Yes. We have got in touch with csv developers and hopefully a github mirror will be set soon.

**Comment by Xynnn007** [comment]
Fixed in https://github.com/confidential-containers/guest-components/pull/448/files
