### ISSUE TITLE
Proposing Magnus Kulke as maintainer for guest-components

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/guest-components#456]
Magnus  (@mkulke ) have been steadily contributing to the guest-components projects, reviewing PRs and design.  I'm proposing Magnus to be added as a maintainer for guest-components to share load with the existing maintainers :-) 

cc @fitzthum @Xynnn007

**Comment by fitzthum** [comment]
+1

**Comment by sameo** [comment]
+1 from me!

**Comment by fitzthum** [comment]
Added! (note that @Xynnn007 gave a thumbs up to the first message)
