### ISSUE TITLE
-v should print the git sha for the guest bins

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#487]
at the moment the `-v` doesn't tell us much, it would be nice to get a git revision.

**Comment by fitzthum** [comment]
On a related note, should we be synchronizing our Cargo versions with the actual release version? It's more work, but it's a bit goofy for everything to be v0.1.0 permanently.

**Comment by mkulke** [comment]
> On a related note, should we be synchronizing our Cargo versions with the actual release version? It's more work, but it's a bit goofy for everything to be v0.1.0 permanently.

yeah, that too. once we release crates we have to do this anyway.
