### ISSUE TITLE
I am not able to encrypt image using provider as parameter using Skopeo command

### ISSUE THREAD

**Issue by prashant9394** [confidential-containers/guest-components#497]

**Comment by prashant9394** [comment]
> _No description provided._

I have come across issue: sudo OCICRYPT_KEYPROVIDER_CONFIG=$(pwd)/attestation-agent/sample_keyprovider/src/enc_mods/offline_fs_kbs/ocicrypt.conf skopeo copy docker://docker.io/library/alpine:latest oci:alpine-encrypt1 --encryption-key provider:attestation-agent:$(pwd)/keys.json:key_id1

**FATA[0000] Invalid encryption keys: Provided protocol not recognized**

**Comment by Xynnn007** [comment]
Hi @prashant9394 Are you using the latest code? Try to follow this https://github.com/confidential-containers/guest-components/tree/main/attestation-agent/coco_keyprovider

**Comment by prashant9394** [comment]
Hi @Xynnn007  I am using the latest code , i tried with the steps mentioned in the repo, have same issue,
/prashant/coco/attestation-agent/coco_keyprovider$ skopeo copy --insecure-policy --encryption-key provider:attestation-agent:sample=true docker://busybox oci:busybox_encrypted:sample
**FATA[0000] Invalid encryption keys: Provided protocol not recognized**

**Comment by Xynnn007** [comment]
@prashant9394 Oh. We now have docker way to encrypt images, just as https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/coco_keyprovider/README.md#docker shows. The dockerfile is https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/docker/Dockerfile.keyprovider and the next release it would be built and pushed to community's repo on `ghcr.io`.

I built locally and uploaded that to my personal repo. You could try with the following commands (this is the same as https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/coco_keyprovider/README.md#docker)

```shell
# Generate a random key to encrypt the image
head -c 32 /dev/urandom | openssl enc > image_key

# Create a dir to store the encrypted image locally. Or, you can just push
# the image to register by changing -d parameter to
# docker://some.registry.io/some-image:encrypted
mkdir output
docker run -v "$PWD/output:/output" xynnn007/cocokeyprovider:v0.9.0 /encrypt.sh \
	-k "$(base64 < image_key)" \
	-i kbs:///some/key/id \
	-s docker://nginx:stable \
	-d dir:/output
```

**Comment by prashant9394** [comment]
@Xynnn007  can we not use skopeo and attestation-agent for encryption rather than creation of docker image and enc key.

**Comment by mkulke** [comment]
You can use the docker file and [/encrypt-image.sh](https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/hack/encrypt-image.sh) as a reference and perform the steps yourself. the error reporting is not great, but it looks like you might be using an outdated version of skopeo that doesn't support that encryption protocol.

**Comment by fitzthum** [comment]
Yeah, my hunch is that you need to update skopeo.

**Comment by fitzthum** [comment]
Closing this. @prashant9394 lmk if the issue has not been resolved.

**Comment by reclock** [comment]
FATA[0000] Invalid encryption keys: Provided protocol not recognized   

I have also encountered this problem, and the solution is to install a new Skypeo v1.14, which requires source code compilation and installation
