### ISSUE TITLE
The error about certificate when pull image

### ISSUE THREAD

**Issue by ZhangLimengLimeng** [confidential-containers/guest-components#505]
After building an initramfs like "kata-containers-initrd.img.online_sev_kbc" and successfully running [docker.io/pawsonfang/busybox:encrypted].
I installed a Harbor registry on the same machine and generated a certificate using the script from https://github.com/confidential-containers/trustee/issues/332. 
The error "is self signed certificate" when pull image.

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  6s    default-scheduler  Successfully assigned default/test-en-hello-world1 to ra
  Normal   Pulling    3s    kubelet            Pulling image "192.168.6.105:8443/library/hello-world:encrypted"
  Warning  Failed     3s    kubelet            Failed to pull image "192.168.6.105:8443/library/hello-world:encrypted": rpc error: code = Internal desc = failed to pull manifest error sending request for url (https://192.168.6.105:8443/v2/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919: (self signed certificate)
  Warning  Failed     3s    kubelet            Error: ErrImagePull
  Normal   BackOff    2s    kubelet            Back-off pulling image "192.168.6.105:8443/library/hello-world:encrypted"
  Warning  Failed     2s    kubelet            Error: ImagePullBackOff
```

I have try other certificate and put the ca.crt into the guest initramfs(/etc/ssl/certs/ca-certificates.crt/), it's said "unable to get local issuer certificate" 

My CoCo version is 0.5.0，so how to generate a certificate that is compatible with image-rs and if there are any related scripts available for this purpose?

**Comment by Xynnn007** [comment]
Are you using the self-signed cert for Harbor? Currently the connection over https of image-rs to a registry should only rely on HTTPS that was root-trusted by built-in CA certificates of the os.

If you want to connect to a self-signed registry, you should add the self-signed public key cert to the ca stores of the guest image (this is dangerous, please ensure what you are doing)

**Comment by ZhangLimengLimeng** [comment]
> Are you using the self-signed cert for Harbor? Currently the connection over https of image-rs to a registry should only rely on HTTPS that was root-trusted by built-in CA certificates of the os.
> 
> If you want to connect to a self-signed registry, you should add the self-signed public key cert to the ca stores of the guest image/initrd (this is dangerous, please ensure what you are doing)

```
cat << EOF > localhost.conf
[req]
default_bits       = 2048
default_keyfile    = localhost.key
distinguished_name = req_distinguished_name
req_extensions     = req_ext
x509_extensions    = v3_ca

[req_distinguished_name]
countryName                 = Country Name (2 letter code)
countryName_default         = CN
stateOrProvinceName         = State or Province Name (full name)
stateOrProvinceName_default = Zhejiang
localityName                = Locality Name (eg, city)
localityName_default        = Hangzhou
organizationName            = Organization Name (eg, company)
organizationName_default    = localhost
organizationalUnitName      = organizationalunit
organizationalUnitName_default = Development
commonName                  = Common Name (e.g. server FQDN or YOUR name)
commonName_default          = 192.168.6.105
commonName_max              = 64

[req_ext]
subjectAltName = @alt_names

[v3_ca]
subjectAltName = @alt_names

[alt_names]
DNS.1   = localhost
DNS.2   = 127.0.0.1
DNS.3   = 192.168.6.105
IP.1   = 192.168.6.105   
EOF

openssl req -x509 -nodes -days 365 \
  -newkey rsa:2048 \
  -keyout localhost.key \
  -out localhost.crt \
  -config localhost.conf
```

I change commonName_default/DNS.3/IP.1 to my ip address in the script. This script is output localhost.key and localhost.crt.
I've modified the certificate configuration in the harbor.yml to make it work，In the browser I can get the certificate.
![图片](https://github.com/confidential-containers/guest-components/assets/59240202/f90ee096-b694-4696-9ac2-1ace3dd3a004)

After that copied the localhost.crt content to /etc/ssl/certs/ca-certificates.crt in initramfs and repack.

**Comment by fitzthum** [comment]
btw @Xynnn007 at some point we should think about how to provision these certs automatically maybe via initdata.

**Comment by Xynnn007** [comment]
@fitzthum right. probably via the config of image rs you've mentioned. No matter who is the carrier of image rs

**Comment by ZhangLimengLimeng** [comment]
```
#gen ca private key
openssl genrsa -out ca.key 2048
#gen ca self-sign cert
openssl req -x509 -new -nodes -sha512 -days 3650 \
 -subj "/C=CN/ST=Beijing/L=Beijing/O=example/OU=Personal/CN=TestRootCA" \
 -key ca.key \
 -out ca.crt
#gen harbor private key
openssl genrsa -out harbor.key 2048
#gen harbor cert v3 data
openssl req -sha512 -new \
    -subj "/C=CN/ST=Beijing/L=Beijing/O=example/OU=Personal/CN=192.168.6.105" \
    -key harbor.key \
    -out harbor.csr

cat > v3.ext <<-EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
extendedKeyUsage =  serverAuth, clientAuth
subjectAltName = @alt_names

[alt_names]
DNS.1=192.168.6.105
DNS.2=localhost
DNS.3=127.0.0.1
IP.1=192.168.6.105
EOF

#gen harbor.cert
openssl x509 -req -sha512 -days 3650 \
    -extfile v3.ext \
    -CA ca.crt -CAkey ca.key -CAcreateserial \
    -in harbor.csr \
    -out harbor.crt

openssl x509 -inform PEM -in harbor.crt -out harbor.cert
```


```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  5s    default-scheduler  Successfully assigned default/test-en-hello-world1 to ra
  Normal   Pulling    1s    kubelet            Pulling image "192.168.6.105:8443/library/hello-world:encrypted"
  Warning  Failed     1s    kubelet            Failed to pull image "192.168.6.105:8443/library/hello-world:encrypted": rpc error: code = Internal desc = failed to pull manifest error sending request for url (https://192.168.6.105:8443/v2/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919: (unable to get local issuer certificate)
  Warning  Failed     1s    kubelet            Error: ErrImagePull
  Normal   BackOff    0s    kubelet            Back-off pulling image "192.168.6.105:8443/library/hello-world:encrypted"
  Warning  Failed     0s    kubelet            Error: ImagePullBackOff
```
I generated separate CA and Harbor certificates using the script above.
Copied the ca.crt content to /etc/ssl/certs/ca-certificates.crt in initramfs and repack it.
The error is “unable to get local issuer certificate” when pull image。
Should I write the certificate to another location in the initramfs, or should the certificate be using a URL instead of an IP address?

**Comment by Xynnn007** [comment]
> Should I write the certificate to another location in the initramfs, or should the certificate be using a URL instead of an IP address?

SAN.IP is enough I think as I have tried this. However, to add a cert to trust anchor I follow the following steps on ubuntu
```shell
# Put the cert
sudo cp XXX /usr/local/share/ca-certificates

# Update the CA store
sudo update-ca-certificates
```

This would update the new certs into `/etc/ssl/certs/ca-certificates.crt` which contains more than one certs to be trusted.

See https://stackoverflow.com/questions/20690833/how-to-run-dpkg-reconfigure-ca-certificates-noninteractively/23885181#23885181

**Comment by ZhangLimengLimeng** [comment]
> SAN.IP is enough I think as I have tried this. However, to add a cert to trust anchor I follow the following steps on ubuntu

Is this "add a cert to trust anchor" referring to the guest's initramfs.img or the host machine?

**Comment by Xynnn007** [comment]
> > SAN.IP is enough I think as I have tried this. However, to add a cert to trust anchor I follow the following steps on ubuntu
> 
> Is this "add a cert to trust anchor" referring to the guest's initramfs.img or the host machine?

The guest, where the image-pull operation occurs.

**Comment by ZhangLimengLimeng** [comment]
> The guest, where the image-pull operation occurs.

It's right now，thankyou.
