### ISSUE TITLE
image-rs | Add public key cert to access self-signed image registry

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#525]
In some cases, users set up their own private image registry and we should provide a way to configure the public key cert to access the registry.

**Comment by Xynnn007** [comment]
New progress. Once https://github.com/confidential-containers/guest-components/pull/608/files is finished, we can consider starting this thread by add configs of private registry public key cert in CDH's image pull config.

**Comment by fitzthum** [comment]
This has been a long time coming. The CDH config is the perfect place to put this.
