### ISSUE TITLE
SEV: Client Broken

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/guest-components#534]
We missed something when we refactored the KBC into the SEV Client.

[Here](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/hub/src/auth/sev.rs#L18) we load the kernel module, but we don't use the kernel module struct as intended. 

The struct has drop implemented on it to unload the kernel module when the struct goes out of scope. This is a precaution to avoid other components accessing the secret.

Since we drop the struct during the auth step, the securityfs will be empty by the time we setup the client.

**Comment by Xynnn007** [comment]
Ohh ohh, let me dive into this.
