### ISSUE TITLE
Promote the error print of guest-components

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#541]
Currently, the error information printed by guest-components is not well-formatted. An expected one from my point of view should looks like
```plaintext
some error
Caused by: level 1 reason
Caused by: some more detailed reason
...
```

This follows the discussion of https://github.com/confidential-containers/trustee/pull/327#discussion_r1503563955

BTW, we should think about whether the concrete error information should be reported to higher level. A most simple way is to report a rough error type to the caller of the guest components, and the concrete guest component itself should log the error information in the format mentioned above.

wdyt? @mkulke and probably @kartikjoshi21

**Comment by mkulke** [comment]
The caller of guest-components would be api-server-rest in this case?

I think we should probably define what is sensible, ASR is mostly a convenience facility, so it would be nice for it to produce some readable error messages. I can image that e.g. a 404 we receive from KBS can be propagated to the ASR response, but for anything else it could be a simple 500 http status, with additional information in the process logs. An in-container user would not be able to resolve an internal error in normal circumstances.

not sure there is a logging crate that will print multiline error traces. we might have to build it ourselves

**Comment by fitzthum** [comment]
Yes, possibly related to https://github.com/confidential-containers/guest-components/issues/529

Also keep in mind that sometimes we should be careful about what error messages are exposed to the host.

**Comment by Xynnn007** [comment]
> not sure there is a logging crate that will print multiline error traces. we might have to build it ourselves

With `thiserror`, we could impl a macro `format_error` where we needs to generate a multiple line error information as mentioned in [the message](https://github.com/confidential-containers/guest-components/issues/541#issue-2242706334)
```rust
macro_rules! format_error {
    ($err:expr) => {{
        let mut error_string = format!("{}", $err);
        let mut current_error = $err.source();
        while let Some(source) = current_error {
            error_string.push_str(&format!("\nCaused by: {}", source));
            current_error = source.source();
        }
        error_string
    }};
}
```


> I think we should probably define what is sensible, ASR is mostly a convenience facility, so it would be nice for it to produce some readable error messages. I can image that e.g. a 404 we receive from KBS can be propagated to the ASR response, but for anything else it could be a simple 500 http status, with additional information in the process logs. An in-container user would not be able to resolve an internal error in normal circumstances.

It makes sense that we should concrete internal error information should be not be delivered. I also agree that your potential point that we should do error truncation before delivering to concrete end user.

Let me make a table to show where the errors information will be exposed to non-guest-components
|Interface|source|
|---|---|
|Host|kata-agent's CDH call <-- CDH API error|
|App container| ASR's web api <-- CDH/AA API error |

so we have two choices to truncate the error information. either in 
1. CDH/AA's API [implementation](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/hub/src/bin/server/mod.rs#L90): Means that CDH/AA will log the whole error information, but with a brief error information in API response.
2. or the caller side ([ASR](https://github.com/confidential-containers/guest-components/blob/main/api-server-rest/src/cdh.rs#L87) and [kata-agent](https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/cdh.rs#L62)): Means that kata-agent and ASR will get the whole error information, but it will only leave the first line of the error and abondon other lines. Related to #529, if error happens in ASR, a 500 http status will be returned.

Both are practical. One thing to note that if we use way 1, a CDH client tool will not get the whole error message. So I am with way 2. The rationale behind is that kata-agent and ASR are all abstract "guest-components", so logs are secure to transfer in-between them.
