### ISSUE TITLE
release: Consider adding the needed vendored code as part of the release

### ISSUE THREAD

**Issue by fidencio** [confidential-containers/guest-components#554]
Distros will perform **offline** builds of the guest-components, in order to package them inside Kata Containers rootfs image / initrd, and it's impossible to do so without having access to the vendored code.

Kata Containers does this by taking advantage of this custom script that's used as part of our release workflow:
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/release/generate_vendor.sh

**Comment by Xynnn007** [comment]
I think this makes great sense if we finally want to achieve hermetic builds for rootfs of CoCo/kata defined in [SLSA](https://slsa.dev/spec/v0.1/levels).
