### ISSUE TITLE
Report Cause of Handshake Failure More Clearly

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/guest-components#564]
Currently we offer a very [general message](https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/kbs_protocol/src/client/rcar_client.rs#L59) when we are unable to connect to the KBS. This isn't ideal. We should propagate at least the error from the last failure upwards.

**Comment by Xynnn007** [comment]
We have a log [here](https://github.com/confidential-containers/guest-components/blob/main/attestation-agent/kbs_protocol/src/client/rcar_client.rs#L61) for every try. So do you mean we record the error information every time fails, and return the latest one if the retries run out?
