### ISSUE TITLE
image-rs: use nix crate instead of unsafe blocks

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#567]
We might want to replace our own unsafe libc invocations with the [nix crate](https://crates.io/crates/nix)'s wrappers, since they provide a rust-native api and we don't have to deal with cstrings and raw pointers.

**Comment by Xynnn007** [comment]
Now we are using nix for all libc calls. see https://github.com/confidential-containers/guest-components/blob/main/image-rs/Cargo.toml
