### ISSUE TITLE
image-rs: make AUTH_FILE_PATH configurable

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#568]
At the moment image-rs looks up auth.json at `kbs:///default/credential/test`. So, a hardcoded confidential resource. we need a way to override this value, so it will consider locations on the file system. 

Image pull credentials as confidential KBS resources are questionable with nydus anyway, since with snapshotters the untrusted node needs access to the same registry for metadata, also for guest-pull.

**Comment by mkulke** [comment]
cc @bpradipt

**Comment by Xynnn007** [comment]
This value can be overriden now. In ImageClient's config->file_paths member.

**Comment by mkulke** [comment]
Indeed, thanks! I assume we need a change in kata then?

Kata's is initializing the image client in a cascade like this currently:

```rust
// agent/src/image.rs
impl ImageService {
    pub fn new() -> Self {
        Self {
            image_client: ImageClient::new(PathBuf::from(KATA_IMAGE_WORK_DIR)),
            images: HashMap::new(),
        }
    }
...
```
```rust
// image-rs/src/image.rs
/// Create an ImageClient instance with specific work directory.
pub fn new(image_work_dir: PathBuf) -> Self {
    let config = ImageConfig::new(image_work_dir);
    ...
}
 ```
 
 ```rust
// image-rs/src/config.rs
impl ImageConfig {
    /// Construct an instance of `ImageConfig` with specific work directory.
    pub fn new(image_work_dir: PathBuf) -> Self {
        Self {
            work_dir: image_work_dir,
            ..Default::default()
        }
    }
...
```

So we'll end up with the default paths. I assume we need an `image_registry_auth_file` option, like we had on CCv0, then?

**Comment by stevenhorsman** [comment]
> Image pull credentials as confidential KBS resources are questionable with nydus anyway

I understand this, but I think that the nydus approach is still a workaround and in future if we move to the containerd image transfer service, we might be able to get away from removing the required for imagePullSecret on the host, so I'd like to avoid painting ourselves into a corner/ potentially investing a lot of time to get the credentials flowed from Kubernetes to the kata-agent, so would advocate for still providing the image pull creds as a confidential resource in the short-term. Just my own opinion though, so happy to be challenged!

**Comment by Xynnn007** [comment]
Yes! I think so --  just like what container policy does. But the left question is containerd would pull manifest on the host side. Although this would not be used when nydus snapshotter would pull manifest again, the pulling on the host side would require auth, or the host side failure would make the whole pulling process fail.

**Comment by mkulke** [comment]
@stevenhorsman

> so would advocate for still providing the image pull creds as a confidential resource.

To make sure I understand the suggestion: as the only option? so the user needs to deploy a trustee kbs?

**Comment by stevenhorsman** [comment]
> @stevenhorsman
> 
> > so would advocate for still providing the image pull creds as a confidential resource.
> 
> To make sure I understand the suggestion: as the only option, so the user needs to deploy a trustee kbs?

So I think we can also continue with the `image_registry_auth_file` config approach, so that if a user wants to edit the guest image they can avoid needing to deploy trustee (and we can use that for peer pods), which is similar to the `CCv0` situation, but apart from that I'm not sure I know of another alternative to get the credentials to image-rs?

**Comment by mkulke** [comment]
Ah understood, but then we need to re-introduce that one in kata, right? we can maybe hide it behind the `guest-pull` feature flag?

**Comment by stevenhorsman** [comment]
> Ah understood, but then we need to re-introduce that one in kata, right? we can maybe hide it behind the (existing) guest-pull feature flag?

Yeah - I will re-visit https://github.com/kata-containers/kata-containers/issues/8122 and mention the `image_registry_auth_file` approach, though we don't have a way to integration test it in kata-containers, but we can ensure that we continue with these tests in peer pods (I'm not sure if they are on any platforms other than ibm cloud, but I guess getting libvirt working would be important as one of our main PR e2e tests)?

**Comment by bpradipt** [comment]
If we want to treat ImagePullSecret as a confidential resource then it will need to work with SealedSecret. Is my understanding correct ?

**Comment by fitzthum** [comment]
> If we want to treat ImagePullSecret as a confidential resource then it will need to work with SealedSecret. Is my understanding correct ?

The sealed secret stuff applies to secrets that are exposed to the workloads. Not sure it is relevant to ImagePullSecret.

Since the authenticated registry is not confidential, I think it would be nice if the KBS wasn't involved. Is there a way to push the credentials used by nydus on the host into the guest?

**Comment by bpradipt** [comment]
> > If we want to treat ImagePullSecret as a confidential resource then it will need to work with SealedSecret. Is my understanding correct ?
> 
> The sealed secret stuff applies to secrets that are exposed to the workloads. Not sure it is relevant to ImagePullSecret.
> 
> Since the authenticated registry is not confidential, I think it would be nice if the KBS wasn't involved. Is there a way to push the credentials used by nydus on the host into the guest?

If ImagePullSecrets are anyway exposed to cluster-admin then it's not a confidential resource and we needn't handle it via KBS. The container image indeed is a confidential resource and decryption or signing key will be retrieved from KBS.
But let's say if we decide to treat ImagePullSecrets as confidential resource, then the imho min expectation will be that it's an encrypted secret.

**Comment by mkulke** [comment]
> But let's say if we decide to treat ImagePullSecrets as confidential resource, then the imho min expectation will be that it's an encrypted secret.

As long as use remote snapshotters (like nydus) instead of "pure" guest-pull via other means, we'd always have to be expose the pull-secret to a k8s node (for metadata), no?

**Comment by bpradipt** [comment]
> > But let's say if we decide to treat ImagePullSecrets as confidential resource, then the imho min expectation will be that it's an encrypted secret.
> 
> As long as use remote snapshotters (like nydus) instead of "pure" guest-pull via other means, we'd always have to be expose the pull-secret to a k8s node (for metadata), no?

Yes

**Comment by Xynnn007** [comment]
> > Ah understood, but then we need to re-introduce that one in kata, right? we can maybe hide it behind the (existing) guest-pull feature flag?
> 
> Yeah - I will re-visit [kata-containers/kata-containers#8122](https://github.com/kata-containers/kata-containers/issues/8122) and mention the `image_registry_auth_file` approach, though we don't have a way to integration test it in kata-containers, but we can ensure that we continue with these tests in peer pods (I'm not sure if they are on any platforms other than ibm cloud, but I guess getting libvirt working would be important as one of our main PR e2e tests)?
> 
> @Xynnn007 - Are you okay with this approach too?

The approach is not clear to me.

To me, with nydus-snapshotter the logic would be
1. containerd try to pull manifest of the image. 
2. If manifest pulling finishes successfully, containerd will call nydus-snapshotter to pull layers; or, the pulling process will fail


So the question is if manifest cannot be pulling on the host without proper plaintext registry auth from a private registry, the pulling process would exit early before nydus-snapshotter receives the pulling requests. For Kata-cc I did not get the point how to deal with that; for peer-pods, there is no snapshotter involved?

**Comment by stevenhorsman** [comment]
> So the question is if manifest cannot be pulling on the host without proper plaintext registry auth from a private registry, the pulling process would exit early before nydus-snapshotter receives the pulling requests. For Kata-cc I did not get the point how to deal with that; for peer-pods, there is no snapshotter involved?

So my proposal is that we set imagePullSecrets on the host, so that nydus-snapshotter can pull the mainfest in the usual way, but then *also* pass the credentials to the guest (image-rs) either via auth.json and `image_registry_auth_file`, or via the KBS/KMS (or some other approach?). This is basically what we did in CC 0.8.0.

Then if/when we move away from the snapshotter approach we can just drop the `imagePullSecret` on host requirement and at back to having the option for confidential credentials?

**Comment by Xynnn007** [comment]
@stevenhorsman thanks for the clarification. makes sense to me

**Comment by Xynnn007** [comment]
@mkulke can we close this issue?

**Comment by mkulke** [comment]
yup
