### ISSUE TITLE
image-rs: Whiteout code causing problems with image pull?

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/guest-components#604]
In kata-containers we tried to bump image-rs to latest in (https://github.com/kata-containers/kata-containers/pull/9828#issuecomment-2197182995) and the pull-image failed on the agnhost:2.21 image. We had quite a bit of discussion in https://cloud-native.slack.com/archives/C039JSH0807/p1719475621870489 and found that the specific error was:
```
error="rpc error: code = Internal desc = failed to handle layer: hasher sha256: channel: send failed SendError { .. }; unpack error: failed to unpack convert whiteout\n\nCaused by:\n    Not supported (os error 95)" name=containerd-shim-v2 pid=40880 
```
We we tried the commit before https://github.com/confidential-containers/guest-components/pull/563 it seemed to work, so there are a few things we probable should do as a result of this:
- Revert the whiteout change until we can understand the problem
- I did try and re-produce the error with the image-rs integration tests and didn't manage it, so understanding that will be important too
- Improving the image-rs errors by adding extra `.context` to unwraps was crucial to debug this, so apply that sounds like a good approach

**Comment by fitzthum** [comment]
cc @skaegi

**Comment by squarti** [comment]
@stevenhorsman @skaegi  I believe the original code failed when running on platforms where xattr is not supported. PR above reintroduces the code on supported platforms.

**Comment by squarti** [comment]
@stevenhorsman Do you know which OS these failures are happening? Curious to know whether it is an unsupported OS or the FS does not suppport xattr.

**Comment by Xynnn007** [comment]
> @stevenhorsman Do you know which OS these failures were happening? Curious to know whether it is an unsupported OS or FS that does not support xattr.

I am afraid that this is because the previous whiteout PR will directly set `xattr` without detecting if current path supports xattr. For some cases, a tmpfs would not support xattr as it is compiled without enable specific feature. I am afraid that #687 also has this problem. We should do some change to align with https://github.com/confidential-containers/guest-components/pull/691 which fixes the `xattr` detecting.

**Comment by squarti** [comment]
> I am afraid that this is because the previous whiteout PR will directly set `xattr` without detecting if current path supports xattr. For some cases, a tmpfs would not support xattr as it is compiled without enable specific feature. I am afraid that #687 also has this problem. We should do some change to align with #691 which fixes the `xattr` detecting.

Makes sense.  I will update #687 once #691 is merged.

**Comment by Xynnn007** [comment]
#691 has been merged
