### ISSUE TITLE
Duplicate `secret_cli.rs` files

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/guest-components#632]
We have two files called `secret_cli.rs`, which is a bit confusing. The first one is [here](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/secret/src/bin/secret_cli.rs). This is the source for the cli tool. There is also [this](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/secret/tests/secret_cli.rs). This is a set of tests that uses the tool.

I think we should consolidate these by simply adding the tests to the main `secret_cli.rs` file. I might give this a try, but I'm a bit worried about breaking things since I cannot run either test without access to various HSMs.

**Comment by Xynnn007** [comment]
The latter does not exist for now.
