### ISSUE TITLE
[Question] Is there any version of kernel that supports extending TDX RTMR?

### ISSUE THREAD

**Issue by kvinwang** [confidential-containers/guest-components#655]
The comment for `runtime_measurement_extend_available` states `the TD runs Linux upstream kernel and is _currently_ not able to do it`.
I'm intrigued about the specific kernel version or patch required for the function to operate. Despite thorough investigation, I've been unable to uncover any relevant information.

**Comment by Xynnn007** [comment]
cc @arronwy

**Comment by mythi** [comment]
> I'm intrigued about the specific kernel version or patch required for the function to operate.

There's no available kernel version yet. The Linux CoCo community is currently working to get the ABI defined. v2 of the generic implementation is [available](https://lore.kernel.org/linux-coco/20240128212532.2754325-1-sameo@rivosinc.com/). I've co-authored the TDX plumbing which we'll post once v3 comes out.

**Comment by kvinwang** [comment]
> There's no available kernel version yet. The Linux CoCo community is currently working to get the ABI defined. v2 of the generic implementation is [available](https://lore.kernel.org/linux-coco/20240128212532.2754325-1-sameo@rivosinc.com/). I've co-authored the TDX plumbing which we'll post once v3 comes out.

Thank you for your prompt response and clarification.

**Comment by mythi** [comment]
> > There's no available kernel version yet. The Linux CoCo community is currently working to get the ABI defined. v2 of the generic implementation is [available](https://lore.kernel.org/linux-coco/20240128212532.2754325-1-sameo@rivosinc.com/). I've co-authored the TDX plumbing which we'll post once v3 comes out.
> 
> Thank you for your prompt response and clarification.

I should add that if you have use-cases for this, it'd be nice to hear your feedback. We have related open issues in this repo (#397, #495, and also #636).
