### ISSUE TITLE
Is the reference to nydus-tools correct for guest-pull?

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/guest-components#657]
We currently have documentation related to nydus tools for encrypted images. I suspect this is related to pulling on the host. For guest-pulling w/ nydus, which we currently use, there is no such requirement, so the docs would be misleading. Should we remove this doc or add a remark that this doesn't apply to guest-pull?

https://github.com/confidential-containers/guest-components/blob/main/image-rs/docs/pull_image_with_nydus.md

**Comment by Xynnn007** [comment]
cc @jiangliu

**Comment by ChengyuZhu6** [comment]
@mkulke This feature allows pulling nydus format images directly in the guest instead in the host, without the installations for the dependencies with nydus stuffs in the guest rootfs.

**Comment by ChengyuZhu6** [comment]
To construct a nydus format image, we need to install nydus dependencies.
