### ISSUE TITLE
CDH｜ Reorganize the sub-crates into module

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/guest-components#811]
Due to #419 from @ChengyuZhu6 , we have a plan to publish some crates of guest-components to crates.io. But now we have the following crates 
```
members = [
    "api-server-rest",
    "attestation-agent/app",
    "attestation-agent/lib",
    "attestation-agent/kbc",
    "attestation-agent/kbs_protocol",
    "attestation-agent/attester",
    "attestation-agent/deps/resource_uri",
    "attestation-agent/deps/crypto",
    "attestation-agent/deps/sev",
    "attestation-agent/coco_keyprovider",
    "attestation-agent/test-binaries",
    "confidential-data-hub/hub",
    "confidential-data-hub/kms",
    "confidential-data-hub/image",
    "confidential-data-hub/secret",
    "confidential-data-hub/storage",
    "image-rs",
    "ocicrypt-rs",
]
```

Some of them might have too universal name like `image`, and thus cause naming clash when `cargo audit`.

Due to [suggestion](https://github.com/confidential-containers/guest-components/issues/419#issuecomment-1953893086) from @mkulke , we are hoping to making some crates into modules.

cc @fitzthum @mythi

**Comment by mkulke** [comment]
- [ ] #812
- [ ] #814
- [ ] kms (deps from other crates, so it's a good idea to do this last)
- [ ] move everything from the `hub` hierarchy into the `./confidential-data-hub` root folder
